### ISSUE TITLE
Doesn't seem to work with Adonis v5

### ISSUE THREAD

**Issue by g33kidd** [lookinlab/adonis-fcm#4]
I've followed the instructions and made sure the tsconfig is updated and the adonisrc file, but I can't seem to get VSCode to understand that it's there? Is this just a Code problem or is something wrong with my setup?

Edit: So some more information, it just keeps saying it can't find the module `@ioc:Adonis/Addons/FCM`

**Comment by LookinGit** [comment]
Hi @g33kidd. Try reload VSCode
